version: "3.8"

services:
  api:
    build:
      context: ./app
    container_name: ai-api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    restart: unless-stopped

  telegram-bot:
    build:
      context: ./app
    container_name: telegram-bot
    command: ["python", "bot.py"]
    depends_on:
      - api
    environment:
      TELEGRAM_TOKEN: 7969284143:AAGE4VsqW4QefQHrd6pp0Op15o_4kJ0VqIM
      API_URL: "http://api:8000/ask"
    restart: unless-stopped